spring:
  config:
    import: optional:file:../etc/.env.properties
  application:
    name: deep-search-embabel-backend
  cloud:
    openfeign:
      client:
        config:
          tavily:
            url: "https://api.tavily.com"
            connect-timeout: 5000
            read-timeout: 10000
            default-request-headers:
              Authorization: "Bearer ${TAVILY_API_KEY}"
embabel:
  agent:
    platform:
      models:
        ollama:
          base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
  models:
    default-llm: llama3.1:8b
    llms:
      fast: llama3.1:8b
      best: llama3.1:8b

server:
  port: 8081
