package org.baramov.search.tavily

import com.fasterxml.jackson.annotation.JsonIgnoreProperties

/**
 * Search result from Tavily.
 * Example response:
 * ```json
 * {
 *   "query": "Who is Leo Messi?",
 *   "answer": "Lionel Messi, born in 1987, is an Argentine footballer widely regarded as one of the greatest players of his generation. He spent the majority of his career playing for FC Barcelona, where he won numerous domestic league titles and UEFA Champions League titles. Messi is known for his exceptional dribbling skills, vision, and goal-scoring ability. He has won multiple FIFA Ballon d'Or awards, numerous La Liga titles with Barcelona, and holds the record for most goals scored in a calendar year. In 2014, he led Argentina to the World Cup final, and in 2015, he helped Barcelona capture another treble. Despite turning 36 in June, Messi remains highly influential in the sport.",
 *   "images": [],
 *   "results": [
 *     {
 *       "title": "Lionel Messi Facts | Britannica",
 *       "url": "https://www.britannica.com/facts/Lionel-Messi",
 *       "content": "Lionel Messi, an Argentine footballer, is widely regarded as one of the greatest football players of his generation. Born in 1987, Messi spent the majority of his career playing for Barcelona, where he won numerous domestic league titles and UEFA Champions League titles. Messi is known for his exceptional dribbling skills, vision, and goal",
 *       "score": 0.81025416,
 *       "raw_content": null,
 *       "favicon": "https://britannica.com/favicon.png"
 *     }
 *   ],
 *   "response_time": "1.67",
 *   "auto_parameters": {
 *     "topic": "general",
 *     "search_depth": "basic"
 *   },
 *   "usage": {
 *     "credits": 1
 *   },
 *   "request_id": "123e4567-e89b-12d3-a456-426614174111"
 * }
 * ```
 * @property query the search query that was executed.
 * @property answer A short answer to the user's query, generated by an LLM.
 * Included in the response only if `include_answer` is requested (i.e., set to `true`, `basic`, or `advanced`)
 * @property images A list of images related to the search query.
 * @property results A list of search results.
 * @property responseTime The time taken to execute the search query.
 * @property autoParameters The auto parameters used to execute the search query.
 * @property usage The usage information for the search query.
 * @property requestId The request ID for the search query.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
data class SearchResult(
    val query: String,
    val answer: String?,
    val images: List<ResultRelatedImage>,
    val results: List<SearchResultItem>,
    val responseTime: String,
    val autoParameters: AutoParameters?,
    val usage: Usage?,
    val requestId: String
)

/**
 * Search result item.
 * @property title The title of the search result.
 * @property url The URL of the search result.
 * @property content A short description of the search result.
 * @property score The relevance score of the search result.
 * @property rawContent The cleaned and parsed HTML content of the search result. Only if include_raw_content is true.
 * @property favicon The favicon URL for the result.
 */
data class SearchResultItem(
    val title: String,
    val url: String,
    val content: String,
    val score: Double,
    val rawContent: String?,
    val favicon: String?
)

/**
 * Search related images, where the description is included only if the query flag `include_image_descriptions`
 * is set to true.
 */
data class ResultRelatedImage(
    val url: String,
    val description: String?
)

data class AutoParameters(
    val topic: String,
    val searchDepth: String
)

data class Usage(
    val credits: Int
)
