package app.dr3

import com.embabel.agent.api.annotation.AchievesGoal
import com.embabel.agent.api.annotation.Action
import com.embabel.agent.api.annotation.Agent
import com.embabel.agent.api.common.OperationContext
import com.embabel.agent.api.event.ProgressUpdateEvent
import org.springframework.context.annotation.Profile

@Agent(
    name = "Mock Deep Research Agent",
    description = "An agent to research a given topic and product a detailed report."
)
@Profile("mock || test")
class MockDeepResearchAgent {

    @Action
    fun planSearch(userInput: UserResearchRequest, context: OperationContext): WebSearchPlan {
        context.processContext.onProcessEvent(
            ProgressUpdateEvent(agentProcess = context.agentProcess, name = "Planning search queries", current = 0, total = 3)
        )
        return WebSearchPlan(
            searches = listOf(
                WebSearchItem(reason = "Overview of the topic", query = "${userInput.researchTopic} overview"),
                WebSearchItem(reason = "Recent developments", query = "${userInput.researchTopic} latest news 2025"),
                WebSearchItem(reason = "In-depth analysis", query = "${userInput.researchTopic} analysis research")
            )
        )
    }

    @Action
    fun executeSearches(webSearchPlan: WebSearchPlan, context: OperationContext): SearchSummaryList {
        context.processContext.onProcessEvent(
            ProgressUpdateEvent(agentProcess = context.agentProcess, name = "Executing searches", current = 1, total = 3)
        )
        Thread.sleep(800)
        val summaries = webSearchPlan.searches.map { item ->
            SearchSummary(
                title = item.query,
                summary = "Mock summary for \"${item.query}\". This is a placeholder result simulating a real web search. " +
                    "The actual search would retrieve relevant articles, synthesize key points, and return a concise paragraph. " +
                    "For frontend development purposes this canned response exercises the full data flow without LLM latency."
            )
        }
        return SearchSummaryList(summaries)
    }

    @Action
    @AchievesGoal(description = "Creates the final deep research report on the given topic")
    fun finalSearchReport(
        userResearchRequest: UserResearchRequest,
        researchResults: SearchSummaryList,
        context: OperationContext
    ): ResearchReport {
        context.processContext.onProcessEvent(
            ProgressUpdateEvent(agentProcess = context.agentProcess, name = "Generating final report", current = 2, total = 3)
        )
        Thread.sleep(1000)
        val topic = userResearchRequest.researchTopic
        return ResearchReport(
            shortSummary = "This is a mock research report on \"$topic\". " +
                "It contains placeholder content to facilitate frontend development without requiring live LLM or search API calls.",
            markdownReport = """
                # Research Report: $topic

                > **Note:** This is a mock report generated by the `mock` Spring profile for frontend development purposes.

                ## Executive Summary

                This report provides a comprehensive overview of **$topic**. The research was conducted using
                three targeted web searches covering an overview, recent developments, and in-depth analysis.

                ## Key Findings

                ### 1. Overview

                ${topic.replaceFirstChar { it.uppercase() }} is a broad and evolving field with significant implications
                across multiple domains. Initial research indicates strong interest from both academic and industry
                stakeholders, with numerous publications and projects emerging in recent years.

                ### 2. Recent Developments (2025)

                The landscape around $topic has shifted considerably in 2025. Several major organizations have announced
                initiatives, and open-source communities have accelerated tooling and framework development. Key trends
                include increased automation, improved accessibility, and cross-disciplinary collaboration.

                ### 3. In-Depth Analysis

                A deeper examination reveals nuanced challenges and opportunities. Practitioners report that while
                foundational concepts are well-established, practical implementation varies widely. Best practices
                continue to emerge, and the community is converging on a set of recommended patterns.

                ## Conclusion

                Research into $topic reveals a dynamic and rapidly maturing field. Continued investment in tooling,
                education, and standardization will be critical to realizing its full potential.

                ## Follow-Up Directions

                - Explore case studies from early adopters
                - Investigate regulatory and compliance considerations
                - Review comparative benchmarks across leading approaches
            """.trimIndent(),
            followUpQuestions = listOf(
                "What are the most common challenges practitioners face with $topic?",
                "How does $topic compare to alternative approaches?",
                "What are the projected trends for $topic over the next 5 years?"
            )
        )
    }
}
