package app.domain

/**
 * Represents a refined or expanded search query generated by the agent.
 *
 * @property originalQuery The query that was refined
 * @property refinedQuery The new refined query string
 * @property rationale Explanation of why this refinement was chosen
 */
data class RefinedQuery(
    val originalQuery: String,
    val refinedQuery: String,
    val rationale: String
)
